add reminder and schedule feature
ritwik12/Virtual-Assistant pull request #102
Opened 2020-10-18 07:09 UTC by vnksnkr

#16 
I've added a reminder feature that writes schedules into a .dat file and reminds the events on a particular day

2020-10-19 20:26 UTC, ritwik12 commented
@vnksnkr Can you also make the README.md changes for this so that one can know how to use this feature.

2020-10-20 03:08 UTC, vnksnkr commented
@ritwik12  Sure! how do I add screenshots?

2020-10-20 21:47 UTC, ritwik12 requested changes
@vnksnkr That's really nice work, Appreciate it. A few changes needs to be done. Please go through those. Also, can you please add an Image of your working feature in a cool way just like we have for all others in the Readme.md in that Reminder section of yours? That would be really nice.

2020-10-20 21:47 UTC, ritwik12 commented on README.md
> +Every time you run the Virtual-Assistant you will recieve notifications of your schedule for that day.If you wish to access schedule for any other day you can give commands like "whats my schedule" o
```suggestion
You can schedule your appointments and work using Virtual-Assistant. It will remind you of the appointments you have on a particular day. You can also access your schedule for any other day by just using the correct words.

In order to add a reminder simply say `Add a reminder` or `Add an appointment` or `Make a schedule` and other things like that. Once there, just enter the required details like date, time and event description.

Every time you run the Virtual-Assistant you will receive notifications of your schedule for that day. If you wish to access schedule for any other day you can say  `my schedule` or `what's my appointments`.
```

2020-10-20 21:47 UTC, ritwik12 commented on src/reminder.c
> +printf("You have %s on %s at %s", search_event.desc,search_event.date,search_event.time);
```suggestion
printf("You have %s on %s at %s \n", search_event.desc,search_event.date,search_event.time);
```

You missed a \n at the end here.

2020-10-20 21:47 UTC, ritwik12 commented on utils/defines.h
> +	},
```suggestion
	[REMINDER] = {
		{"set, "reminder"},
		{"remind", "me"},
		{"Add", "reminder"},
		{"Make", "schedule"},
		{"make", "an", "appointment"}
	},
	[SCHEDULE] = {
		{"show", "my", "schedule"},
		{"schedule", "today's"},
		{"What's", "my", "schedule"},
		{"Do", "I", "have", "appointments"},
	},
```

2020-10-20 21:49 UTC, ritwik12 commented
@vnksnkr One important thing that I want to tell you which I noticed while going through your README and codes. You assumed that these are commands to make virtual assistant perform some tasks. No it isn't, we use AI here to make virtual assistant understand what the user wants. Those words are the keywords in the knowledge base only. Not the exact commands. You can know more from README.md

2020-10-21 12:16 UTC, ritwik12 approved these changes

2020-10-21 12:16 UTC, merged

2020-10-21 12:16 UTC, ritwik12 commented
@vnksnkr Thanks a lot!!

2020-12-15 18:06 UTC, ritwik12 commented
@all-contributors please add @vnksnkr for code and doc

2020-12-15 18:10 UTC, ritwik12 commented
@all-contributors please add @vnksnkr for code and doc

2020-12-15 18:12 UTC, ritwik12 commented
@all-contributors please add @vnksnkr for code and doc